//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Repository
{
    using System;
    using System.Collections.Generic;
    
    using CRM.Model;
   using CRM.IRepository;
    using System.Threading.Tasks;
    using System.Linq.Expressions;

    /// <summary>
    /// 负责每个数据表的数据操作
    /// </summary>
    public partial class sysRoleRepository : BaseRepository<sysRole>, IsysRoleRepository
    {
        #region 针对此表的特殊操作写在此处

        #endregion
        public Task<List<sysRole>> QueryByPage<TKey>(int pageindex, int pagesize, out int rowcount, Expression<Func<sysRole, TKey>> order, Expression<Func<sysRole, bool>> where, bool OrderByType = false)
        {
            throw new NotImplementedException();
        }

        public Task<Tuple<List<sysRole>>> QueryOrderBy<TKey>(Expression<Func<sysRole, bool>> where, Expression<Func<sysRole, TKey>> order)
        {
            throw new NotImplementedException();
        }

        public Task<List<sysRole>> QueryOrderByDescending<TKey>(Expression<Func<sysRole, bool>> where, Expression<Func<sysRole, TKey>> order)
        {
            throw new NotImplementedException();
        }

        public Task<List<TResult>> RunProc<TResult>(string sql, params object[] pamrs)
        {
            throw new NotImplementedException();
        }
    }
}
